* Collect Earth Online

/Crowdsourced visual interpretation of on-demand satellite imagery/

This is a Java 10 application written with the Spark web framework
(http://sparkjava.com).

** Installation

In order to build and run Collect Earth Online, you will need:

- Java Development Kit 1.10+
- Either Maven 3.3.9+ or Gradle 3.3+
- Tomcat 8+ (optional)

** Running with an Embedded Jetty Webserver

This is the simplest solution to get up and running quickly. The
application will be available at http://localhost:8080.

*** With Maven

#+begin_src sh
mvn compile exec:java
#+end_src

*** With Gradle

#+begin_src sh
gradle run
#+end_src

** Running inside Tomcat

This allows multiple web applications to share the same host and port
on your machine. You will need to install a recent version of Tomcat
(version 8+ recommended) to use this method. The application will be
available at http://localhost:8080/ceo.

*** With Maven

#+begin_src sh
mvn package
export TOMCAT_HOME="where/you/installed/tomcat"
sudo ln -s $PWD/target/collect-earth-online-<version>.war $TOMCAT_HOME/webapps/ceo.war
sudo $TOMCAT_HOME/bin/startup.sh
#+end_src

*** With Gradle

#+begin_src sh
gradle build
export TOMCAT_HOME="where/you/installed/tomcat"
sudo ln -s $PWD/build/libs/collect-earth-online-<version>.war $TOMCAT_HOME/webapps/ceo.war
sudo $TOMCAT_HOME/bin/startup.sh
#+end_src

** Building OpenForis Collect

In order to easily exchange information with OpenForis' other software
products, Collect Earth Online (CEO) shares a database with OpenForis
Collect. Access to this database is made through REST API calls to the
Collect web application running on the same host as CEO. In order to
build and launch Collect, follow these steps:

1. Install Maven 3.5.0+. You can download the latest version here:
   https://maven.apache.org/download.cgi

2. Set M2_HOME to the directory where you installed this version of
   Maven.

#+begin_src sh
export M2_HOME="/where/you/installed/maven-3.5.0"
#+end_src

3. Clone the collect repository and package it as a WAR file.

#+begin_src sh
git clone https://github.com/openforis/collect.git
cd collect
git checkout ceo
mvn clean
mvn verify
sudo ln -s $PWD/collect-web/collect-webapp/target/collect.war $TOMCAT_HOME/webapps/collect.war
#+end_src

4. Create $TOMCAT_HOME/conf/Catalina/localhost/collect.xml with the
   following contents (but replace "/your/home/directory" in the url
   field with the path to your actual home directory):

#+begin_src nxml
<?xml version="1.0" encoding="UTF-8" ?>

<Context path="/collect" reloadable="false">
  <Parameter name="collect.simple_editor" value="false" />
  <Resource
      name="jdbc/collectDs"
      auth="Container"
      type="javax.sql.DataSource"
      factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
      driverClassName="org.h2.Driver"
      url="jdbc:h2:/your/home/directory/.openforis/collect;AUTO_SERVER=true">
  </Resource>
</Context>
#+end_src

5. Create the ".openforis" directory referenced in the above url field
   to hold Collect's database.

#+begin_src sh
mkdir /your/home/directory/.openforis
#+end_src

6. Launch Tomcat.

#+begin_src sh
sudo $TOMCAT_HOME/bin/startup.sh
#+end_src

The Collect web application should now be running at http://localhost:8080/collect.

** Building OpenForis Users

In order to share user logins and user groups across the various
OpenForis software products, we need to install a final web
application called OpenForis Users. To build and launch Users, follow
these steps:

1. Like CEO, Users needs to be built with a recent version of Maven.
   Set M2_HOME to the directory where you installed Maven 3.3.9+.

#+begin_src sh
export M2_HOME="/where/you/installed/maven-3.3.9"
#+end_src

2. Clone the users repository and package it as a WAR file.

#+begin_src sh
git clone https://github.com/openforis/users.git
cd users
mvn clean
mvn generate-sources -Pcode-gen
mvn package
sudo ln -s $PWD/target/of-users.war $TOMCAT_HOME/webapps/of-users.war
#+end_src

3. Create $TOMCAT_HOME/conf/Catalina/localhost/of-users.xml with the
   following contents (but replace "/your/home/directory" in the url
   field with the path to your actual home directory):

#+begin_src nxml
<?xml version="1.0" encoding="UTF-8" ?>

<Context path="/of-users" reloadable="false">
  <Resource
      name="jdbc/of-users-ds"
      auth="Container"
      type="javax.sql.DataSource"
      factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
      driverClassName="org.h2.Driver"
      url="jdbc:h2:/your/home/directory/.openforis/of-users;AUTO_SERVER=true">
  </Resource>
</Context>
#+end_src

4. Create the ".openforis" directory referenced in the above url field
   to hold Collect's database.

#+begin_src sh
mkdir /your/home/directory/.openforis
#+end_src

5. Add the H2 JAR file to the $TOMCAT_HOME/lib directory. You can
   download it from here:
   http://repo2.maven.org/maven2/com/h2database/h2/1.4.193/h2-1.4.193.jar

6. Launch Tomcat.

#+begin_src sh
sudo $TOMCAT_HOME/bin/startup.sh
#+end_src

** Contact

*Authors:*
- Gary W. Johnson (SIG)
- David S. Saah (SIG)
- Billy Ashmall (NASA)
- Stefano Ricci (FAO)
- Roberto Fontanarosa (FAO)
- Alfonso SanchezPausDiaz (FAO)

*Emails:*

- gjohnson@sig-gis.com
- dsaah@sig-gis.com
- billy.ashmall@nasa.gov
- stefano.ricci@fao.org
- roberto.fontanarosa@fao.org
- alfonso.sanchezpausdiaz@fao.org
