* Collect Earth Online

Crowd-sourced visual interpretation of on-demand satellite imagery

** Installation Requirements

*** Required

- [[https://jdk.java.net][Java Development Kit (version 14)]]
- [[https://clojure.org/guides/getting_started][Clojure CLI tools 1.10]]
- [[https://www.postgresql.org/download][Postgresql (version 12)]]
- [[https://postgis.net/install/][PostGIS (version 3)]]
- [[https://www.7-zip.org/][p7zip]]
- [[https://nodejs.org/en/][node 10]]

** Application Configuration

On startup, the Pyregence application reads a file called config.edn
in the toplevel directory of this repository, which contains various
user-configurable system parameters. A sample file called
config.default.edn is provided with this repository to get you
started. To begin, simply rename (or copy) it to config.edn. Then edit
it according to the following sections.

Please note that you must replace all values surrounded with angle
brackets (e.g., "<api-key>") with actual values for the application to
work correctly. While most of the fields should be self-explanatory,
the ~:wildfire-camera-api-key~ field may not be. This is simply an API
key for the [[http://alertwildfire.org][AlertWildfire]] API.

** Postgresql Database Setup

*Postgresql* needs to be installed on the machine that will be hosting
this website. This installation task is system specific and is beyond
the scope of this README, so please follow the instructions for your
operating system and Postgresql version. However, please ensure that
the database server's superuser account is named "postgres" and that
you know its database connection password before proceeding.

Once the Postgresql database server is running on your machine, you
should navigate to the toplevel directory (i.e., the directory
containing this README) and run the database build command as follows:

#+begin_src sh
clojure -M:build-db build-all
#+end_src

This will begin by creating a new database and role called ceo and
then add the postgis and pgcrypto extensions to it. Next, the script
will populate the database with the schemas, tables, and functions
that are necessary for storing and processing ceo's data. Finally, it
will load some default data into these tables that is necessary for
the website to function properly.

*** Performance Settings

If you want to improve the performance of your Postgresql server, one
way is to visit the [[https://pgtune.leopard.in.ua/][pgtune]] website
and input your system settings. This will generate a set of configuration
options that you can add to the postgresql.conf file in your system-specific
Postgresql data directory.

If you would like to keep these settings separate for your own
reference, you can add them to a file called "performance.conf" that
you should place in your Postgresql data directory. You can then
import these settings into postgresql.conf by adding this line to the
end of that file:

#+begin_example
include = 'performance.conf'
#+end_example

Note that the Postgresql server will need to be restarted for these
changes to take effect.

** Environment Variable Setup

In order for your command line shell to find the programs installed
above, you will need to update your environment variables. Under
GNU/Linux, *BSD, or MacOS X, you can set these through your shell's
.*rc or .*profile configuration files in your $HOME directory. In a
Windows environment, you will need to set either the USER (for the
current user only) or SYSTEM (for any user) environment variables
under your system settings menu.

*** Step 1: Add JAVA_HOME

On a Unix machine using bash (e.g., GNU/Linux or MacOS X):

#+begin_src sh
export JAVA_HOME=<jdk-installation-directory>
#+end_src

On a Unix machine using csh or tcsh (e.g., *BSD):

#+begin_src sh
setenv JAVA_HOME <jdk-installation-directory>
#+end_src

On a Windows machine:

#+begin_example
JAVA_HOME = C:\Program Files\Java\jdk-X.X.X
#+end_example

Replace *X.X.X* with the JDK version installed on your computer.

*** Step 2: Update PATH

On a Unix machine using bash (e.g., GNU/Linux or MacOS X):

#+begin_src sh
export PATH=$PATH:$JAVA_HOME/bin
#+end_src

On a Unix machine using csh or tcsh (e.g., *BSD):

#+begin_src sh
setenv PATH $PATH\:$JAVA_HOME/bin
#+end_src

On a Windows machine, add these entries to the PATH environment
variable:

#+begin_example
%JAVA_HOME%\bin
C:\Program Files\PostgreSQL\X\lib
C:\Program Files\PostgreSQL\X\bin
C:\Program Files\7-Zip
#+end_example

Replace *X* with the PostgreSQL version installed on your computer.

** Development Web Server

*** Compile and run

To compile and run the web application, navigate to the top level
project directory and run:

#+begin_src sh
npm install
npm run webpack-dev
clojure -M:build-db functions
clojure -M:run-server -m dev [-p 8080] [-P 8443]
#+end_src

The website will then be available at http://localhost:8080 unless a
port is specified. An http port can be specified with -p and an https
port can be specified with -P. In dev mode, server-side exceptions
will be displayed in the browser and Clojure source files will be
reloaded whenever you refresh the page.

*** Checking for Reflection Warnings

From the toplevel project directory run:

#+begin_src sh
clojure -M:check-reflection
#+end_src

This will emit warnings when reflection is needed to resolve Java
method calls or field accesses. To resolve any that appear, add
[[https://clojure.org/reference/java_interop#typehints][type hints]]
to your code. Resolving all reflection warnings can improve
system performance.

** Production Web Server

*** Installation Requirements

- [[https://certbot.eff.org/][certbot]]
- [[https://www.openssl.org/source/][openssl]]

*** Email Server

To set up the email server for system emails, open the "config.edn" file in
the root directory of the application. Edit the default EDN object containing
server details to the file, replacing the values with your own.

*** Enabling HTTPS

If you have not already created a SSL certificate, you must start the server
without a https port specified.

#+begin_src sh
clojure -M:run-server
#+end_src

To automatically create an SSL certificate signed by [[https://letsencrypt.org][Let's Encrypt]],
simply run the following command from your shell:

#+begin_src sh
clojure -M:https --certbot-init -d mydomain.com [-p certbot-dir]
#+end_src

Note: If your certbot installation stores its config files in a
directory other than /etc/letsencrypt, you should specify it with the
optional certbot-dir argument to certbot-init.

The certbot-init command will first create a shell script in the
directory containing this README, called certbot-deploy-hook.sh. Next,
it sends a request to the Let's Encrypt servers for a new signed SSL
certificate and sets certbot-deploy-hook.sh to run automatically when
the new certificate is received. When executed, this script will
repackage the new certificate into a format that can be understood by
our web server.

While there should be no need to do so, if you ever want to perform
this repackaging step manually, simply run this command from your
shell:

#+begin_src sh
clojure -M:https --package-cert -d mydomain.com [-p certbot-dir]
#+end_src

Certbot runs as a background task every 12 hours and will renew any
certificate that is set to expire in 30 days or less. Each time the
certificate is renewed, certbot-deploy-hook.sh will be run
automatically to repackage the updated certificate into the correct
format.

*** Forwarding Ports

Forwarding ports from the defaults for http and https allows the web server
to run without sudo privileges. To forward ports use iptables. Installing
iptables-persistent after setting up the routing will automatically save
the rules persistently.

#+begin_src sh
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
sudo iptables -t nat -I PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
sudo iptables-save
sudo apt -y install iptables-persistent
#+end_src

*** Building GEE-Gateway

In order to use the Geo-Dash portion of CEO, we need to install an
application to communicate with Google Earth Engine called
GEE-Gateway. To build and launch GEE-Gateway, download its source code
from https://github.com/openforis/gee-gateway and follow the steps in
its README file.

*** Launching the Web Server

To compile and run the web application, navigate to the top level
project directory and run:

#+begin_src sh
npm install
npm run webpack-prod
clojure -M:build-db functions -d ceo
clojure -M:run-server -m [dev|prod] [-p 8080] [-P 8443]
#+end_src

The website will then be available at http://localhost:8080 unless a
port is specified. An http port can be specified with -p and an https
port can be specified with -P. In dev mode, server-side exceptions
will be displayed in the browser and Clojure source files will be
reloaded whenever you refresh the page. These features are disabled in
prod mode. If -m is unspecified, it will default to prod mode.

*** Maintaining Daily Logs

By default the server will log to standard out. If you would like to
have the system log to YYYY-DD-MM.log, use the "-o path" option to
specify an output path. You can either specify a path relative to
the toplevel directory of this repository or an absolute path on
your filesystem. The logger will keep the 10 most recent logs.

*** Using the Announcement Banner

On each page load clojure will read the value of announcement.txt. If text is
found, the value will be inserted into a HTML element that displays as a red
banner at the top of the page. To add a new announcement, edit
announcement.txt and add a new message.  To remove the announcement, edit
announcement.txt and remove all text.

** Contact

*Authors:*
- [[mailto:gjohnson@sig-gis.com][Gary W. Johnson (SIG)]]
- [[mailto:dsaah@sig-gis.com][David S. Saah (SIG)]]
- [[mailto:billy.ashmall@nasa.gov][Billy Ashmall (NASA)]]
- [[mailto:githika.tondapu@nasa.gov][Githika Tondapu (NASA)]]
- [[mailto:stefano.ricci@fao.org][Stefano Ricci (FAO)]]
- [[mailto:roberto.fontanarosa@fao.org][Roberto Fontanarosa (FAO)]]
- [[mailto:alfonso.sanchezpausdiaz@fao.org][Alfonso SanchezPausDiaz (FAO)]]
- [[mailto:mspencer@sig-gis.com][Matt Spencer (SIG)]]
- [[mailto:bbhandari@sig-gis.com][Biplov Bhandari (SIG)]]

** License and Distribution

Copyright © 2016-2020 FAO.

Collect Earth Online is distributed by FAO under the terms of the MIT
License. See LICENSE in this directory for more information.
