* Collect Earth Online

Crowd-sourced visual interpretation of on-demand satellite imagery

** Installation Requirements

- [[https://www.oracle.com/technetwork/java/javase/downloads/index.html][Java Development Kit (version 14)]]
- [[https://clojure.org/guides/getting_started][Clojure CLI tools]]
- [[https://www.postgresql.org/download][Postgresql (version 12)]]
- [[https://postgis.net/install/][Postgis (version 3)]]
- [[https://www.7-zip.org/][p7zip]]
- [[https://www.sqlite.org/download.html][sqlite3]]
- [[https://certbot.eff.org/][certbot]]
- [[https://www.openssl.org/source/][openssl]]

** Postgresql Database Setup

*PostgreSQL* needs to be installed on the machine that will be hosting
this website. Once the Postgresql database server is running on your
machine, you should navigate to the toplevel directory and run the
database build command as follows:

#+begin_src sh
$ clojure -A:build-db build-all
#+end_src

This will begin by creating a new database and role called
ceo and then add the pgcrypto extension to it. Next, the
script will populate the database with the schemas, tables, and
functions that are necessary for storing and processing ceo's
data. Finally, it will load some default data into these tables that
is necessary for the website to function properly.

** Email Server

To set up the email server for system emails, start by creating a file
named `mail-server.edn` in the root directory of the application. Add
the following EDN object containing server details to the file,
replacing the values with your own:

#+begin_src clojure
{:host                  "smtp.gmail.com"
 :user                  "support-my-domain@gmail.com"
 :pass                  "foobarbaz200"
 :ssl                   true
 :base-url              "https://my.domain/"
 :recipient-limit       100
 :mailing-list-interval 600}
#+end_src

** Enabling https

Create a certificate with certbot following the installation instructions
for your OS and environment. Then use openssl to package the certificates
into pkcs12 format. The server looks for keystore.pkcs12 in .key/ and
uses the passcode "foobar". To get the initial key the server must be
running in dev mode to allow http access to certbot.

An example process for an Ubuntu Linux system is as follows:

#+begin_src sh
$ sudo certbot certonly --webroot -w ./resources/public -d mydomain.com
$ sudo openssl pkcs12 -export -out ./.key/keystore.pkcs12
       -in /etc/letsencrypt/live/mydomain.com/fullchain.pem
       -inkey /etc/letsencrypt/live/mydomain.com/privkey.pem
       -passout pass:foobar
#+end_src

The cert creation and renewal can be run automatically with the following command:

#+begin_src sh
$ clojure -A:ssl-key-gen mydomain.com
#+end_src

** Forwarding Ports

Forwarding ports from the defaults for http and https allows the web server
to run without sudo privileges. To forward ports use iptables. Installing
iptables-persistent after setting up the routing will automatically save
the rules persistently.

#+begin_src sh
$ iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
$ iptables -t nat -I PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
$ iptables-save
$ apt -y install iptables-persistent
#+end_src

** Web Server

To compile and run the web application, navigate to the toplevel
project directory and run:

#+begin_src sh
$ npm run webpack-[dev|prod]
$ clojure -A:run-server [port] [dev|prod]
#+end_src

The website will then be available at http://localhost:8080 or on
whichever port you specified. In dev mode, server-side exceptions will
be displayed in the browser and Clojure source files will be reloaded
whenever you refresh the page. These features are disabled in prod
mode. If the second argument to run-server is omitted, it will default
to prod mode.

** Contact

*Authors:*
- [[mailto:gjohnson@sig-gis.com][Gary W. Johnson (SIG)]]
- [[mailto:dsaah@sig-gis.com][David S. Saah (SIG)]]
- [[mailto:billy.ashmall@nasa.gov][Billy Ashmall (NASA)]]
- [[mailto:githika.tondapu@nasa.gov][Githika Tondapu (NASA)]]
- [[mailto:stefano.ricci@fao.org][Stefano Ricci (FAO)]]
- [[mailto:roberto.fontanarosa@fao.org][Roberto Fontanarosa (FAO)]]
- [[mailto:alfonso.sanchezpausdiaz@fao.org][Alfonso SanchezPausDiaz (FAO)]]
- [[mailto:mspencer@sig-gis.com][Matt Spencer (SIG)]]
- [[mailto:bbhandari@sig-gis.com][Biplov Bhandari (SIG)]]
