* Collect Earth Online

Crowd-sourced visual interpretation of on-demand satellite imagery

** Installation Requirements

*** Required

- [[https://jdk.java.net][Java Development Kit (version 14)]]
- [[https://clojure.org/guides/getting_started][Clojure CLI tools 1.10]]
- [[https://www.postgresql.org/download][Postgresql (version 12)]]
- [[https://postgis.net/install/][PostGIS (version 3)]]
- [[https://www.7-zip.org/][p7zip]]
- [[https://nodejs.org/en/][node 10]]

*** Optional / For Production

- [[https://certbot.eff.org/][certbot]]
- [[https://www.openssl.org/source/][openssl]]

** Postgresql Database Setup

*Postgresql* needs to be installed on the machine that will be hosting
this website. This installation task is system specific and is beyond
the scope of this README, so please follow the instructions for your
operating system and Postgresql version. However, please ensure that
the database server's superuser account is named "postgres" and that
you know its database connection password before proceeding.

Once the Postgresql database server is running on your machine, you
should navigate to the toplevel directory (i.e., the directory
containing this README) and run the database build command as follows:

#+begin_src sh
clojure -M:build-db build-all
#+end_src

This will begin by creating a new database and role called ceo and
then add the postgis and pgcrypto extensions to it. Next, the script
will populate the database with the schemas, tables, and functions
that are necessary for storing and processing ceo's data. Finally, it
will load some default data into these tables that is necessary for
the website to function properly.

If you want to improve the performance of your Postgresql server, one
way is to visit the [[https://pgtune.leopard.in.ua/][pgtune]] website and input your system settings.
This will generate a set of configuration options that you can add to
the postgresql.conf file in your system-specific Postgresql data
directory.

If you would like to keep these settings separate for your own
reference, you can add them to a file called "performance.conf" that
you should place in your Postgresql data directory. You can then
import these settings into postgresql.conf by adding this line to the
end of that file:

#+begin_example
include = 'performance.conf'
#+end_example

Note that the Postgresql server will need to be restarted for these
changes to take effect.

** Email Server

To set up the email server for system emails, start by creating a file
named "mail-config.edn" in the root directory of the application. Add
the following EDN object containing server details to the file,
replacing the values with your own:

#+begin_src clojure
{:host                  "smtp.gmail.com"
 :user                  "support-my-domain@gmail.com"
 :pass                  "foobarbaz200"
 :tls                   true
 :port                  587
 :base-url              "https://my.domain/"
 :recipient-limit       100
 :mailing-list-interval 600}
#+end_src

** Enabling HTTPS

To automatically create an SSL certificate signed by [[https://letsencrypt.org][Let's Encrypt]],
simply run the following command from your shell:

#+begin_src sh
clojure -A:certbot-init mydomain.com [certbot-dir]
#+end_src

Note: If your certbot installation stores its config files in a
directory other than /etc/letsencrypt, you should specify it with the
optional certbot-dir argument to certbot-init.

The certbot-init command will first create a shell script in the
directory containing this README, called certbot-deploy-hook.sh. Next,
it sends a request to the Let's Encrypt servers for a new signed SSL
certificate and sets certbot-deploy-hook.sh to run automatically when
the new certificate is received. When executed, this script will
repackage the new certificate into a format that can be understood by
our web server.

While there should be no need to do so, if you ever want to perform
this repackaging step manually, simply run this command from your
shell:

#+begin_src sh
clojure -M:package-cert mydomain.com [certbot-dir]
#+end_src

Certbot runs as a background task every 12 hours and will renew any
certificate that is set to expire in 30 days or less. Each time the
certificate is renewed, certbot-deploy-hook.sh will be run
automatically to repackage the updated certificate into the correct
format.

** Forwarding Ports

Forwarding ports from the defaults for http and https allows the web server
to run without sudo privileges. To forward ports use iptables. Installing
iptables-persistent after setting up the routing will automatically save
the rules persistently.

#+begin_src sh
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
sudo iptables -t nat -I PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
sudo iptables-save
sudo apt -y install iptables-persistent
#+end_src

** Web Server

To compile and run the web application, navigate to the top level
project directory and run:

#+begin_src sh
npm install
npm run webpack-<dev|prod>
clojure -M:run-server [-m <dev|prod>] [-p 8080] [-P 8443]
#+end_src

The website will then be available at http://localhost:8080 unless a
port is specified. An http port can be specified with -p and an https
port can be specified with -P. In dev mode, server-side exceptions
will be displayed in the browser and Clojure source files will be
reloaded whenever you refresh the page. These features are disabled in
prod mode. If the second argument to run-server is omitted, it will
default to prod mode.

** Building GEE-Gateway

In order to use the Geo-Dash portion of CEO, we need to install an
application to communicate with Google Earth Engine called
GEE-Gateway. To build and launch GEE-Gateway, download its source code
from https://github.com/openforis/gee-gateway and follow the steps in
its README file.

** Contact

*Authors:*
- [[mailto:gjohnson@sig-gis.com][Gary W. Johnson (SIG)]]
- [[mailto:dsaah@sig-gis.com][David S. Saah (SIG)]]
- [[mailto:billy.ashmall@nasa.gov][Billy Ashmall (NASA)]]
- [[mailto:githika.tondapu@nasa.gov][Githika Tondapu (NASA)]]
- [[mailto:stefano.ricci@fao.org][Stefano Ricci (FAO)]]
- [[mailto:roberto.fontanarosa@fao.org][Roberto Fontanarosa (FAO)]]
- [[mailto:alfonso.sanchezpausdiaz@fao.org][Alfonso SanchezPausDiaz (FAO)]]
- [[mailto:mspencer@sig-gis.com][Matt Spencer (SIG)]]
- [[mailto:bbhandari@sig-gis.com][Biplov Bhandari (SIG)]]

** License and Distribution

Copyright © 2016-2020 FAO.

Collect Earth Online is distributed by FAO under the terms of the MIT
License. See LICENSE in this directory for more information.
