<#include "header.ftl">
<#include "branding-banner.ftl">
<#include "navbar.ftl">
<#include "start-content.ftl">
<#include "flash-messages.ftl">
<#include "ceo-description.ftl">
<#include "select-project.ftl">
<#include "end-content.ftl">
<#include "institution-banner.ftl">
<#include "footer.ftl">
