<#include "header.ftl">
<#include "branding-banner.ftl">
<#include "navbar.ftl">
<#include "start-content.ftl">
<#include "flash-messages.ftl">
<#include "ceo-description.ftl">
<#include "institution-list.ftl">
<#include "project-list.ftl">
<#include "user-list.ftl">
<#include "end-content.ftl">
<#include "footer.ftl">
